### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by marksev1** [pepijndevos/bicycle_gps#1]
Since there are two ino's I'm confused how to use it. Should i just use bicycle_gps.ino?

Can I use it without the barometer?

Which joystick do you use?

**Comment by pepijndevos** [comment]
Both. It's one Arduino project with 2 files in it. But yes, bicyvle_gps.ino
is the main one.

**Comment by marksev1** [comment]
What about the joystick, is it a normal one, do you use it for moving through the menu?

**Comment by pepijndevos** [comment]
I don't seem to have any picture of the map with street names, but I have a
video of me zooming out.
https://www.youtube.com/watch?v=QvVO6pY9WNY
It's a bit flashy, because everytime it finishes drawing it zooms out and
starts over again.
Normally I'll only redraw periodically to update your position.

**Comment by pepijndevos** [comment]
This blogpost also contains some more information
http://pepijndevos.nl/2014/11/02/open-hardware-gps-navigator.html

**Comment by pepijndevos** [comment]
It's this one:
http://www.adafruit.com/products/512
It's currently only used for zooming, as there are no menues yet.

**Comment by marksev1** [comment]
My last question is, do you have maybe some screenshots how the stuff on the display looks like. Then I'll close the issue :D ...Edit: thanks for the link to the blog!
